version: "3.9"

services:
  mysql:
    image: mysql:8.0.32
    restart: always
    container_name: mysql

    volumes:
      - "./sqlscript/initDB.sql:/docker-entrypoint-initdb.d/1.sql"

    environment:
      - MYSQL_ROOT_PASSWORD=rootroot
      - MYSQL_DATABASE=mall_demo
      - MYSQL_USER=wen
      - MYSQL_PASSWORD=12345
      - LANG=C.UTF-8
      - TZ=Asia/Taipei

    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

    expose:
      - 3306
    ports:
      - "3306:3306"
    networks:
      - default

networks:
  default: