version: "3.9"

services:
  mysql:
    image: mysql:8.0.32
    environment:
      - MySQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=spingbootdb
      - MYSQL_USER=wen
      - MYSQL_PASSWORD=12345
    expose:
      - 3306
    ports:
      - "3306:3306"
    networks:
      - default

networks:
  default: